/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.aguamarina.pr;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int btn_check_off=0x7f020000;
        public static final int btn_check_on=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int logotipo=0x7f020003;
        public static final int splashaguamarina2=0x7f020004;
    }
    public static final class id {
        public static final int ScrollView01=0x7f060007;
        public static final int about1=0x7f060000;
        public static final int about11=0x7f060001;
        public static final int about2=0x7f060004;
        public static final int app_name=0x7f060016;
        public static final int app_repo=0x7f060018;
        public static final int app_ver=0x7f060017;
        public static final int appicon=0x7f060015;
        public static final int baz_src=0x7f06001f;
        public static final int btn1=0x7f06001d;
        public static final int btn_save=0x7f060035;
        public static final int bzr=0x7f06001e;
        public static final int cat_count=0x7f060022;
        public static final int clear_cache=0x7f060036;
        public static final int cntrl=0x7f060020;
        public static final int descript=0x7f06001c;
        public static final int down_n=0x7f06000c;
        public static final int down_txt=0x7f06000b;
        public static final int dwn=0x7f06001a;
        public static final int edit_uri=0x7f060005;
        public static final int groupbtn=0x7f060027;
        public static final int groupshow=0x7f06002c;
        public static final int icon_count=0x7f06003b;
        public static final int imagebutton=0x7f060037;
        public static final int img=0x7f060031;
        public static final int isinst=0x7f060025;
        public static final int isupdt=0x7f060026;
        public static final int l1=0x7f060008;
        public static final int n1=0x7f060009;
        public static final int n11=0x7f06000a;
        public static final int n2=0x7f06000d;
        public static final int n22=0x7f06000e;
        public static final int n3=0x7f06000f;
        public static final int n33=0x7f060010;
        public static final int n4=0x7f060011;
        public static final int n44=0x7f060012;
        public static final int n5=0x7f060013;
        public static final int n55=0x7f060014;
        public static final int name=0x7f060021;
        public static final int nameup=0x7f060024;
        public static final int not=0x7f060003;
        public static final int numberapks=0x7f060033;
        public static final int org_abc=0x7f060029;
        public static final int org_dwn=0x7f06002b;
        public static final int org_rat=0x7f06002a;
        public static final int org_rct=0x7f060028;
        public static final int pbar=0x7f060038;
        public static final int pbar1=0x7f06003a;
        public static final int pbar2=0x7f06003c;
        public static final int pkg=0x7f060023;
        public static final int rating=0x7f060019;
        public static final int rem_lst=0x7f06002f;
        public static final int repo_count=0x7f060039;
        public static final int sec_msg=0x7f060006;
        public static final int shw_all=0x7f06002e;
        public static final int shw_ct=0x7f06002d;
        public static final int site=0x7f060002;
        public static final int size=0x7f06001b;
        public static final int uri=0x7f060032;
        public static final int user_pass_dialog_root=0x7f060034;
        public static final int vw1=0x7f060030;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int addrepo=0x7f030001;
        public static final int alertscroll=0x7f030002;
        public static final int apkinfo=0x7f030003;
        public static final int bzzsrch=0x7f030004;
        public static final int catglist=0x7f030005;
        public static final int list=0x7f030006;
        public static final int listicons=0x7f030007;
        public static final int orderpopup=0x7f030008;
        public static final int remrepo=0x7f030009;
        public static final int repolist=0x7f03000a;
        public static final int repolisticons=0x7f03000b;
        public static final int repologin=0x7f03000c;
        public static final int settings=0x7f03000d;
        public static final int start=0x7f03000e;
        public static final int tablist=0x7f03000f;
        public static final int updatebars=0x7f030010;
    }
    public static final class string {
        public static final int about_alrt=0x7f050006;
        public static final int about_mail=0x7f05005a;
        public static final int about_site=0x7f050059;
        public static final int about_txt1=0x7f050057;
        public static final int about_txt11=0x7f050058;
        public static final int about_txt2=0x7f05005b;
        public static final int about_txt3=0x7f05005c;
        public static final int add_repo_private=0x7f050029;
        public static final int add_repo_text=0x7f050028;
        public static final int aguamarina_error=0x7f050016;
        public static final int app_name=0x7f050049;
        public static final int app_pop_up_no_info=0x7f05001b;
        public static final int base_path=0x7f050047;
        public static final int btn_add=0x7f050041;
        public static final int btn_cancel=0x7f050042;
        public static final int btn_chlog=0x7f050044;
        public static final int btn_done=0x7f050043;
        public static final int btn_no=0x7f05003f;
        public static final int btn_ok=0x7f050040;
        public static final int btn_search_market=0x7f050045;
        public static final int btn_yes=0x7f05003e;
        public static final int change_log_url=0x7f05004b;
        public static final int clear_cache_btn=0x7f050034;
        public static final int download_alrt=0x7f05000f;
        public static final int dwn_n=0x7f050002;
        public static final int error_download_alrt=0x7f05000e;
        public static final int error_no_market=0x7f05001c;
        public static final int error_on_update=0x7f050021;
        public static final int fetch_apk=0x7f050015;
        public static final int icons_path=0x7f050046;
        public static final int info_path=0x7f050048;
        public static final int install=0x7f050005;
        public static final int installed=0x7f050052;
        public static final int installed_update=0x7f050053;
        public static final int instver=0x7f050004;
        public static final int isinst=0x7f050003;
        public static final int lstver=0x7f050001;
        public static final int manage_repo_add=0x7f050017;
        public static final int manage_repo_answ_cc=0x7f050019;
        public static final int manage_repo_answ_lr=0x7f05001a;
        public static final int manage_repo_answ_wrongl=0x7f050018;
        public static final int md5_error=0x7f050010;
        public static final int menu_about=0x7f050039;
        public static final int menu_add_repo=0x7f05003b;
        public static final int menu_edit_repo=0x7f05003d;
        public static final int menu_manage=0x7f050036;
        public static final int menu_order=0x7f050037;
        public static final int menu_rem_repo=0x7f05003c;
        public static final int menu_search=0x7f05003a;
        public static final int menu_settings=0x7f050038;
        public static final int menu_update_repo=0x7f050035;
        public static final int myrepo_alrt=0x7f05000c;
        public static final int network_error=0x7f050011;
        public static final int newrepo_alrt=0x7f05000d;
        public static final int no_found=0x7f05004f;
        public static final int no_repo=0x7f050050;
        public static final int not_inst=0x7f050051;
        public static final int order_popup_catg1=0x7f050030;
        public static final int order_popup_catg2=0x7f050031;
        public static final int order_popup_lst1=0x7f05002b;
        public static final int order_popup_lst2=0x7f05002c;
        public static final int order_popup_lst3=0x7f05002d;
        public static final int order_popup_lst4=0x7f05002e;
        public static final int order_popup_title=0x7f050032;
        public static final int order_popup_title1=0x7f05002a;
        public static final int order_popup_title2=0x7f05002f;
        public static final int rem=0x7f050007;
        public static final int remote_in_noSD=0x7f05001f;
        public static final int remote_in_noSD_title=0x7f05001e;
        public static final int remote_in_noSDspace=0x7f050020;
        public static final int repo_alrt=0x7f05000a;
        public static final int save_btn=0x7f050033;
        public static final int settings_cache=0x7f05001d;
        public static final int srch_hint=0x7f050056;
        public static final int srch_label=0x7f050055;
        public static final int srv_version=0x7f050054;
        public static final int tab_avail=0x7f05004c;
        public static final int tab_inst=0x7f05004d;
        public static final int tab_updt=0x7f05004e;
        public static final int title_repo_alrt=0x7f05000b;
        public static final int top_download=0x7f050014;
        public static final int top_error=0x7f050013;
        public static final int top_please_wait=0x7f050012;
        public static final int up_server=0x7f050000;
        public static final int update=0x7f050008;
        public static final int update_alrt=0x7f050009;
        public static final int update_main=0x7f050024;
        public static final int update_repos=0x7f050023;
        public static final int updating_3g=0x7f050025;
        public static final int updating_cfrm=0x7f050026;
        public static final int updating_msg=0x7f050022;
        public static final int updating_norepos=0x7f050027;
        public static final int ver_str=0x7f05004a;
    }
    public static final class xml {
        public static final int find=0x7f040000;
    }
}
